services:
  app:
    build:
      context: .
      target: production
    image: volttechafrica/flexdeskbackend:latest
    container_name: flexdesk-backend
    restart: unless-stopped
    environment:
      - NODE_NO_WARNINGS=${NODE_NO_WARNINGS}
      - PORT=${PORT}
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}
      - ENV=${ENV}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - JWT_REFRESH_EXPIRATION=${JWT_REFRESH_EXPIRATION}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_USER=${REDIS_USER}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - DATADOG_API_KEY=${DATADOG_API_KEY}
      - DATADOG_APP_KEY=${DATADOG_APP_KEY}
      - DD_AGENT_HOST=datadog-agent
      - DD_AGENT_PORT=${DD_AGENT_PORT}
    env_file:
      - .env
    networks:
      - flexdesk-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v2/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    security_opt:
      - no-new-privileges:true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"


networks:
  flexdesk-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16