services:
  datadog-agent:
    image: datadog/agent:latest
    container_name: datadog-agent
    restart: unless-stopped
    environment:
      - DD_API_KEY=${DATADOG_API_KEY}
      - DD_SITE=datadoghq.eu
      - DD_DOGSTATSD_PORT=8125
      - DD_PROCESS_AGENT_ENABLED=true
      - DD_SYSTEM_PROBE_ENABLED=true
      - DD_APM_ENABLED=true
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_METRICS_ENABLED=true
      - DD_SYSTEM_PROBE_NETWORK_ENABLED=true
      - DD_SYSTEM_PROBE_PROCESS_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
      - DD_AGENT_HOST=datadog-agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    ports:
      - "8125:8125/udp" # DogStatsD
      - "8126:8126"     # APM
    networks:
      - flexdesk-network
    cap_add:
      - SYS_ADMIN
      - SYS_PTRACE
      - NET_ADMIN
      - NET_BROADCAST
      - NET_RAW
      - IPC_LOCK
      - CHOWN
      - SYS_RESOURCE
    security_opt:
      - apparmor:unconfined
    healthcheck:
      test: ["CMD", "agent", "health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  dashboard-publisher:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    environment:
      - DD_API_KEY=${DATADOG_API_KEY}
      - DD_APP_KEY=${DATADOG_APP_KEY}
    depends_on:
      - app
    networks:
      - flexdesk-network
    restart: on-failure:3
    healthcheck:
      test: ["CMD", "curl", "-f", "https://api.datadoghq.eu/api/v1/validate"]
      interval: 30s
      timeout: 10s
      retries: 3


networks:
  flexdesk-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

